import json, os

OUT = r"C:\Users\megha\OneDrive\Desktop\conv claude\app\src\main\assets\scenarios_batch3.json"

def make_nodes(sid, prefix, acts, win_say):
    nodes = {}
    for ai, act in enumerate(acts, 1):
        next_bridge = f"{prefix}_a{ai+1}_bridge" if ai < 8 else f"{prefix}_win"
        bid = f"{prefix}_a{ai}_bridge"
        nodes[bid] = {"nodeId":bid,"type":"bridge","scenarioId":sid,"say":act[0],"hint":None,"visual":"nod","expectedKeywords":[],"minKeywordsRequired":1,"successNode":f"{prefix}_a{ai}_q1","retryNode":None,"failNode":None,"maxRetries":2,"isTerminal":False,"starValue":0}
        for si, step in enumerate(act[1], 1):
            say, kws, hint, teach = step[0], step[1], step[2], step[3]
            vis = step[4] if len(step) > 4 else "nod"
            nxt = f"{prefix}_a{ai}_q{si+1}" if si < 5 else next_bridge
            qid = f"{prefix}_a{ai}_q{si}"; rid = f"{prefix}_a{ai}_q{si}_r"; tid = f"{prefix}_a{ai}_q{si}_t"
            nodes[qid] = {"nodeId":qid,"type":"prompt","scenarioId":sid,"say":say,"hint":hint,"visual":vis,"expectedKeywords":kws,"minKeywordsRequired":1,"successNode":nxt,"retryNode":rid,"failNode":tid,"maxRetries":2,"isTerminal":False,"starValue":0}
            nodes[rid] = {"nodeId":rid,"type":"prompt","scenarioId":sid,"say":"No worries! Give it another try. "+say,"hint":hint,"visual":"nod","expectedKeywords":kws,"minKeywordsRequired":1,"successNode":nxt,"retryNode":tid,"failNode":tid,"maxRetries":1,"isTerminal":False,"starValue":0}
            nodes[tid] = {"nodeId":tid,"type":"teach","scenarioId":sid,"say":"No problem! You could say: "+teach+". Let's keep going.","hint":None,"visual":"point","expectedKeywords":[],"minKeywordsRequired":1,"successNode":nxt,"retryNode":None,"failNode":None,"maxRetries":2,"isTerminal":False,"starValue":0}
    wid = f"{prefix}_win"
    nodes[wid] = {"nodeId":wid,"type":"celebrate","scenarioId":sid,"say":win_say,"hint":None,"visual":"cheer","expectedKeywords":[],"minKeywordsRequired":1,"successNode":None,"retryNode":None,"failNode":None,"maxRetries":2,"isTerminal":True,"starValue":1}
    return nodes

SCENARIOS_DATA = [
    # 21 overwhelmed
    ("overwhelmed","Saying You Feel Overwhelmed","Practice telling someone when you have too much going on.","🌊","#B3E5FC","ow",
     "Amazing! You told someone you were overwhelmed and asked for help. That is so brave! You earned a star!",
     [
      ("Let us practice what to do when everything feels like too much.",
       [("How do you feel right now? Can you name your feeling?",["overwhelmed","stressed","anxious","tired","too much","lot"],"Say: I feel overwhelmed","I feel really overwhelmed right now","think"),
        ("Good. Who could you tell when you feel overwhelmed?",["teacher","friend","parent","counselor","someone","adult"],"Say: I could tell a teacher or friend","I could tell my teacher or a trusted friend","nod"),
        ("What would you say to start the conversation?",["excuse me","can i talk","need help","moment","second"],"Say: Excuse me, can I talk to you?","Excuse me, can I talk to you for a moment","wave"),
        ("How would you explain what is happening?",["too much","lot going on","stressed","hard","struggling","overwhelmed"],"Say: I have a lot going on right now","I have too much going on and I am struggling","think"),
        ("What kind of help could you ask for?",["break","help","talk","rest","support","advice"],"Say: Could I have a short break?","Could I take a short break or talk to someone","point"),
       ]),
      ("You started the conversation. Now explain more.",
       [("The adult says: Tell me more. What is making you feel this way?",["homework","test","friends","noise","class","everything","school"],"Name what is stressing you","My homework and the test on Friday are stressing me out","think"),
        ("They ask: Is there one thing that feels biggest right now?",["test","homework","project","friend","class","one thing"],"Pick the main thing","The test coming up feels the biggest right now","nod"),
        ("They say: That sounds hard. How long have you felt this way?",["few days","week","today","yesterday","while","long"],"Say how long","I have felt this way for a few days now","sad"),
        ("They ask: Did you sleep okay last night?",["yes","no","little","not much","some","okay","bad"],"Answer honestly","No I did not sleep very well last night","sad"),
        ("They say: Thank you for telling me. How can I help?",["break","talk","help","rest","quiet","different"],"Say what would help","A short break and somewhere quiet would really help","point"),
       ]),
      ("They are helping you make a plan.",
       [("They suggest: What if we break your tasks into smaller steps?",["yes","sure","okay","sounds good","please","that helps"],"Say yes","Yes that sounds really helpful thank you","nod"),
        ("They ask: Which task should we start with?",["homework","reading","math","one","first","easiest","small"],"Name a task","Let us start with the easiest one first","think"),
        ("They say: Good choice. How much time do you need for that?",["minutes","hour","thirty","twenty","little","short","while"],"Give a time","Maybe about thirty minutes for that one","nod"),
        ("They ask: Do you want someone to check in with you while you work?",["yes","please","sure","that would help","okay"],"Answer","Yes please that would help me stay on track","nod"),
        ("They say: You can do this. What will you do first?",["start","begin","read","open","write","sit down"],"Name your first action","I will sit down and open my notebook first","point"),
       ]),
      ("After a short break you feel a bit better.",
       [("They check in: How are you feeling now?",["better","little better","okay","still tired","calmer","good"],"Say how you feel","I feel a little better now thank you","nod"),
        ("They ask: Did the break help?",["yes","it did","helped","little","some","kind of"],"Answer","Yes it helped me calm down a bit","nod"),
        ("They say: I am glad. Is there anything else you need?",["no","i think","okay now","maybe later","that is all","fine"],"Answer politely","I think I am okay now but I may need help later","nod"),
        ("They say: Remember you can always come to me. What will you do next time?",["ask","tell","come to you","talk","reach out","get help"],"Say what you will do","Next time I will ask for help sooner","point"),
        ("They say: Great plan. Anything else before you go back?",["no","thank you","that is all","i am ready","okay"],"Close politely","No thank you so much for listening and helping me","wave"),
       ]),
      ("Let us practice some calming strategies.",
       [("When you feel overwhelmed a deep breath helps. Can you say: I will take a deep breath?",["deep breath","breathe","breath","calm","slow"],"Say: I will take a deep breath","I will take a deep breath to calm down","nod"),
        ("Another strategy is counting. Can you say: I will count to ten?",["count","ten","numbers","counting","one two"],"Say: I will count to ten","I will count slowly to ten in my head","nod"),
        ("You could also write it down. Can you say: I will write down how I feel?",["write","journal","list","down","paper","note"],"Say: I will write it down","I will write down how I feel and why","point"),
        ("Talking to a friend can also help. Can you say: I will call a friend?",["call","text","talk","friend","reach out","message"],"Say: I will talk to a friend","I will call or text a friend I trust","wave"),
        ("Which strategy feels easiest for you?",["breath","count","write","friend","talk","call"],"Pick one","I think deep breathing feels easiest for me right now","think"),
       ]),
      ("Let us practice asking a teacher for a break.",
       [("You walk up to your teacher. What do you say first?",["excuse me","hi","sorry to bother","teacher","hey"],"Say: Excuse me","Excuse me, do you have a second","wave"),
        ("Teacher looks up. What do you say next?",["overwhelmed","stressed","lot","hard","struggling","much"],"Explain how you feel","I am feeling really overwhelmed and I need a moment","think"),
        ("Teacher says: Of course. What do you need?",["break","quiet","outside","water","bathroom","walk"],"Name what you need","Could I step outside for a quick break please","point"),
        ("Teacher says: Yes, five minutes. What do you say?",["thank you","thanks","appreciate","grateful"],"Say thank you","Thank you so much I really appreciate it","nod"),
        ("After the break you return. What do you say?",["back","ready","feeling better","thank you","okay now"],"Check back in","I am back and feeling much better now thank you","nod"),
       ]),
      ("Let us talk about what you can do on your own.",
       [("What is something you can do alone when you feel overwhelmed?",["breathe","walk","music","rest","quiet","water","sit"],"Name one strategy","I can sit somewhere quiet and breathe slowly","nod"),
        ("How long should you try calming down before asking for help?",["few minutes","five","short","little while","try first"],"Say a time","I should try for a few minutes first","nod"),
        ("What if the calming strategy does not work?",["ask","tell","get help","find someone","talk to adult"],"Say what to do","Then I should go and ask an adult for help","point"),
        ("Is it okay to ask for help when you feel overwhelmed?",["yes","always","okay","fine","normal","should","right"],"Say yes","Yes it is always okay to ask for help","nod"),
        ("Who is one person you could go to at school?",["teacher","counselor","coach","friend","principal","staff"],"Name someone","I would go to my counselor or homeroom teacher","wave"),
       ]),
      ("Final practice: putting it all together.",
       [("You feel overwhelmed in the hallway. What is your first step?",["breathe","stop","calm","deep breath","pause"],"Pause and breathe","I would stop and take a slow deep breath first","nod"),
        ("Now you need to tell someone. What do you say?",["excuse me","i need","overwhelmed","help","moment","stressed"],"Start the conversation","Excuse me I am feeling overwhelmed and need some help","wave"),
        ("They ask what happened. What do you say?",["lot","too much","hard","everything","school","stress"],"Explain briefly","I have a lot going on and it all hit me at once","think"),
        ("They offer to help. What do you say?",["thank you","yes","please","appreciate","that helps"],"Accept gratefully","Thank you yes please that would mean a lot","nod"),
        ("After the talk how do you feel?",["better","calmer","good","relieved","okay","helped"],"Say you feel better","I feel calmer and better now thank you","nod"),
       ]),
     ]),
    # 22 left_out
    ("left_out","Talking About Feeling Left Out","Practice speaking up when you feel excluded.","💔","#F8BBD9","lo",
     "Well done! You talked about feeling left out and asked to be included. That takes real courage! You earned a star!",
     [
      ("It can hurt to feel left out. Let us practice talking about it.",
       [("How do you feel when you are not included?",["left out","sad","hurt","alone","lonely","upset","excluded"],"Say: I feel left out","I feel really left out and a little hurt","sad"),
        ("Who do you feel left out by?",["friends","classmates","group","team","them","people","lunch table"],"Say who","My friends or the group I usually sit with","sad"),
        ("How do you know you were left out?",["not invited","no one told","they went without","ignored","not asked"],"Describe what happened","They made plans and did not tell me or invite me","sad"),
        ("How long have you felt this way?",["today","yesterday","few days","week","while","long time"],"Say how long","It has been happening for a few days now","sad"),
        ("Is there someone you could talk to about it?",["friend","teacher","parent","counselor","someone","adult"],"Name someone","I could talk to a trusted friend or my counselor","think"),
       ]),
      ("Let us practice talking to a friend about it.",
       [("You see your friend. How do you start the conversation?",["hey","excuse me","can we talk","moment","second","do you have"],"Start gently","Hey do you have a minute to talk","wave"),
        ("Friend says sure. What do you say?",["felt left out","not included","plans","did not invite","heard about"],"Explain","I heard about the plans and felt left out because I was not invited","sad"),
        ("Friend says they did not mean to. How do you respond?",["okay","understand","but it hurt","still felt","just want to know"],"Respond calmly","I understand but it still hurt my feelings","nod"),
        ("Friend apologizes. What do you say?",["thank you","okay","appreciate","means a lot","glad you told me"],"Accept the apology","Thank you for saying that it means a lot to me","nod"),
        ("Friend asks to include you next time. What do you say?",["yes","that would be great","happy","appreciate","love that"],"Say yes","Yes that would make me really happy thank you","nod"),
       ]),
      ("Sometimes you need to ask to be included.",
       [("Your group is making plans. How do you ask to join?",["can i come","join","include me","what are you doing","sounds fun"],"Ask to join","Hey that sounds fun can I come along","wave"),
        ("They say they were not sure you wanted to come. What do you say?",["yes","definitely","love to","want to come","please include"],"Say you want to join","I definitely want to come I would love to be included","nod"),
        ("They ask what time works for you. What do you say?",["anytime","weekend","after school","saturday","sunday","free"],"Name a time","I am free on Saturday afternoon or after school","nod"),
        ("They agree on a time. What do you say?",["great","perfect","see you","excited","sounds good","thank you"],"Respond positively","Great I am excited to come thank you for including me","nod"),
        ("Before you go how do you confirm the plan?",["so we","confirm","remind me","where","what time","meeting"],"Confirm the plan","So we are meeting Saturday at three right","think"),
       ]),
      ("What if someone left you out on purpose?",
       [("You think it was on purpose. What do you do first?",["calm","breathe","think","not sure","make sure","find out"],"Stay calm first","I would take a breath and make sure I have the right information","nod"),
        ("You decide to ask them directly. What do you say?",["feel left out","not included","was it","did you","want to ask","on purpose"],"Ask directly","I felt left out and I wanted to ask if something is wrong","think"),
        ("They say nothing is wrong. How do you respond?",["okay","good","just checking","wanted to make sure","glad"],"Accept their answer","Okay I am glad nothing is wrong I just wanted to check","nod"),
        ("But you still feel hurt. What do you do?",["talk","counselor","parent","friend","write","journal","process"],"Process the feeling","I would still talk to a trusted adult about how I feel","sad"),
        ("What would help you feel better going forward?",["include","invite","ask next time","more communication","honest"],"Say what you need","It would help if people just let me know what is going on","point"),
       ]),
      ("Let us talk about feelings after being left out.",
       [("It is normal to feel sad. Can you say: It is okay to feel sad sometimes?",["okay","normal","allowed","feel sad","sometimes","fine"],"Say it is okay","It is okay and normal to feel sad sometimes","nod"),
        ("What can you do when you feel sad about being left out?",["talk","write","music","rest","walk","breathe","friend"],"Name one thing","I can talk to a friend or write in my journal","nod"),
        ("Is it okay to tell someone your feelings were hurt?",["yes","okay","should","right","always","fine"],"Say yes","Yes it is always okay to say your feelings were hurt","nod"),
        ("What if no one is available to talk right now?",["wait","write","breathe","music","come back","later","journal"],"Say what to do","I would write it down or listen to music and come back later","nod"),
        ("After talking how do you usually feel?",["better","relieved","good","lighter","okay","helped"],"Say how you feel","I usually feel better and more relieved after talking about it","nod"),
       ]),
      ("Let us practice with a counselor.",
       [("You knock on the counselor door. What do you say?",["hi","excuse me","can i talk","moment","need help","second"],"Greet them","Hi do you have a moment I need to talk about something","wave"),
        ("Counselor says come in. What do you say?",["left out","excluded","friends","feel","hurt","hard","not invited"],"Start talking","I have been feeling left out by my friends lately and it has been hard","sad"),
        ("They ask: How long has this been happening?",["few days","week","while","started","lately","this week"],"Say how long","It started about a week ago and has been bothering me","sad"),
        ("They ask: Have you talked to your friends about it?",["no","not yet","tried","nervous","did not know how","scared"],"Answer","Not yet I was not sure how to bring it up","think"),
        ("They offer to help you practice. What do you say?",["yes","please","that would help","love that","thank you","okay"],"Accept","Yes please that would really help me thank you","nod"),
       ]),
      ("Preparing to talk to your friend group.",
       [("You decide to speak up. What do you say to the group?",["hey","can i say","something i wanted","talk to you all","moment"],"Address the group","Hey I wanted to say something to you all if that is okay","wave"),
        ("You explain you have been feeling left out. What words do you use?",["left out","not included","felt like","plans without me","hurt"],"Use feeling words","I have been feeling left out when plans are made without me","sad"),
        ("A friend says sorry we did not realize. How do you respond?",["thank you","okay","appreciate","means a lot","glad"],"Accept kindly","Thank you for saying that I appreciate it","nod"),
        ("You want to make it easier in the future. What do you suggest?",["let me know","include me","invite","group chat","ask me","tell me"],"Make a suggestion","Maybe we could use a group chat to plan things together","think"),
        ("Everyone agrees. How do you close the conversation?",["great","perfect","thank you","happy","glad we talked","appreciate"],"Close positively","I am really glad we talked about it thank you everyone","nod"),
       ]),
      ("Final full practice.",
       [("You feel left out at lunch. What is your first thought?",["talk","say something","ask","breathe","approach","reach out"],"Think of an action","I should say something instead of just sitting alone","think"),
        ("You approach the table. What do you say?",["hi","hey","can i sit","is it okay","mind if i join","room for me"],"Ask to join","Hey is there room for me to sit here today","wave"),
        ("They say sure. You feel relieved. What do you say?",["thank you","thanks","glad","appreciate","happy","great"],"Say thanks","Thank you I am really glad to sit with you all","nod"),
        ("Later you tell a friend it has been hard lately. What do you say?",["left out","hard","felt alone","needed to say","wanted you to know"],"Be honest","I wanted you to know I have felt left out lately and it has been hard","sad"),
        ("They say they are glad you told them. What do you say?",["me too","glad","thanks","needed to hear","means a lot","appreciate"],"Close warmly","Me too it really means a lot that you care","nod"),
       ]),
     ]),
    # 23 ask_forgiveness
    ("ask_forgiveness","Asking Someone to Forgive You","Practice giving a genuine apology and asking for forgiveness.","🌱","#DCEDC8","fg",
     "Wonderful! You gave a sincere apology and asked for forgiveness. That shows real maturity! You earned a star!",
     [
      ("Asking for forgiveness is not easy. Let us practice together.",
       [("What does it mean to apologize?",["sorry","admit","wrong","mistake","hurt","regret","own up"],"Say: admitting you were wrong","Admitting you made a mistake and saying you are sorry","think"),
        ("When should you apologize?",["hurt","wrong","mistake","did something","upset","offended"],"Say when to apologize","When you hurt someone or did something wrong","nod"),
        ("What makes a good apology?",["sincere","honest","mean it","no excuses","genuine","real"],"Say sincere and honest","A good apology is sincere and honest with no excuses","think"),
        ("What should you NOT say in an apology?",["but","if","maybe","not my fault","you made me","excuse"],"Say no buts","You should not say but or make excuses in an apology","nod"),
        ("Are you ready to practice saying sorry?",["yes","ready","okay","sure","let us","go ahead"],"Say yes","Yes I am ready to practice saying sorry","nod"),
       ]),
      ("Let us start the apology conversation.",
       [("You walk up to the person you hurt. What do you say first?",["hey","excuse me","can we talk","have a minute","moment","need to say"],"Ask to talk","Hey do you have a minute I need to say something important","wave"),
        ("They say okay. What is the first thing you say?",["sorry","i am sorry","wanted to apologize","i owe you","messed up"],"Say sorry","I am really sorry for what happened","sad"),
        ("They look at you. What did you do wrong? Say it clearly.",["said","did","hurt","wrong","mistake","embarrassed","left out","ignored"],"Name what you did","I said something that was hurtful and I should not have done that","sad"),
        ("They listen. What do you say to show you understand their feelings?",["know","understand","must have felt","hurt","upset","imagine","realize"],"Show empathy","I understand that must have really hurt your feelings","nod"),
        ("What do you promise going forward?",["wont","will not","never","change","do better","more careful","not again"],"Make a promise","I promise I will be more careful and not do that again","nod"),
       ]),
      ("Going deeper in the apology.",
       [("They say: Why did you do it?",["did not think","mistake","not thinking","wrong","stupid","moment","impulse"],"Be honest","I was not thinking clearly and I made a mistake","sad"),
        ("They ask: Did you mean to hurt me?",["no","did not","never","did not mean","accident","sorry","not intentional"],"Say it was not on purpose","No I never meant to hurt you I am truly sorry","sad"),
        ("They say: It still hurt. How do you respond?",["i know","understand","right","valid","you are right","should not have"],"Validate their feeling","I know and you are right it should not have happened","nod"),
        ("They ask: What will you do differently?",["think before","pause","consider","ask","more careful","stop myself","respect"],"Say your plan","I will think before I speak and consider how my words affect you","think"),
        ("You ask: Can you forgive me?",["forgive","another chance","move on","try again","okay","fresh start"],"Ask for forgiveness","Can you please forgive me I would really like to move forward","sad"),
       ]),
      ("They need time to think about forgiving you.",
       [("They say: I need some time. How do you respond?",["okay","understand","take your time","no rush","whenever you are ready","respect"],"Respect their needs","Okay I completely understand take all the time you need","nod"),
        ("You want to show you are genuine. What do you do?",["nothing","wait","give space","respect","not push","be patient"],"Give them space","I will give you space and not push you to decide","nod"),
        ("Later they check in. They ask if you meant what you said. What do you say?",["yes","absolutely","meant it","genuine","sincere","truly","from heart"],"Say you meant it","Yes I absolutely meant every word I was genuine","nod"),
        ("They say they are thinking about it. How do you respond?",["thank you","okay","appreciate","no rush","waiting","whenever"],"Be patient","Thank you for considering it I am still here whenever you are ready","nod"),
        ("They say: I accept your apology. What do you say?",["thank you","means a lot","appreciate","glad","relieved","grateful"],"Respond gratefully","Thank you so much that means everything to me","nod"),
       ]),
      ("After forgiveness — rebuilding trust.",
       [("They forgave you. How do you feel?",["relieved","happy","grateful","glad","better","thankful"],"Say how you feel","I feel so relieved and grateful thank you","nod"),
        ("How do you show you have changed?",["actions","keep promise","show not tell","be better","consistent","follow through"],"Say actions matter","I will show through my actions not just my words","point"),
        ("They want to move on. What do you say about the past?",["leave behind","fresh start","move forward","not bring up","new chapter"],"Say let us move on","Let us leave it in the past and have a fresh start","nod"),
        ("You want to do something kind for them. What could it be?",["help","kind gesture","lunch","note","compliment","include","time"],"Name one kind thing","I could write them a kind note or do something helpful for them","think"),
        ("What did you learn from this experience?",["think before","words matter","feelings matter","be careful","important","valuable"],"Share what you learned","I learned that words matter and I need to think before I speak","think"),
       ]),
      ("Practicing a specific apology scenario.",
       [("You interrupted a friend in class and embarrassed them. How do you start the apology?",["sorry","apologize","about earlier","class","interrupted","embarrassed"],"Name what you did","I am sorry about what happened in class when I interrupted you","sad"),
        ("They say it was embarrassing. How do you acknowledge that?",["know","understand","must have been","embarrassing","sorry for that","right"],"Acknowledge the embarrassment","I know that must have been embarrassing and I am truly sorry","sad"),
        ("They ask: Why did you do it?",["not thinking","rushed","did not realize","wrong","impulse","mistake"],"Be honest","I was not thinking and I just blurted it out which was wrong","sad"),
        ("They say okay but not to do it again. What do you say?",["promise","will not","never","understood","learned","wont happen"],"Agree and promise","I promise I will not do it again I have learned from this","nod"),
        ("You ask: Are we okay?",["yes","we good","fine","okay","forgiven","moving on","sure"],"Ask if you are okay","Are we okay I really value our friendship","wave"),
       ]),
      ("What if the person does not forgive you right away?",
       [("They say they are not ready to forgive. How do you respond?",["okay","understand","respect","take your time","no rush","whenever"],"Respect their choice","I understand and I respect that please take all the time you need","nod"),
        ("You feel disappointed. What do you do with that feeling?",["okay","accept","feel","process","talk to someone","journal","breathe"],"Process it","I accept the disappointment and I will talk to someone I trust","nod"),
        ("Should you keep pressuring them to forgive you?",["no","should not","give space","not pressure","let them","wrong to push"],"Say no","No I should not pressure them I need to give them space","nod"),
        ("What can you do while you wait?",["be kind","show change","consistent","give space","patient","nothing"],"Say be patient","I can be kind and patient and show I have changed through my actions","point"),
        ("If they never forgive you what can you do?",["accept","okay","learn","move on","keep growing","forgive yourself","try"],"Accept and grow","I can accept it learn from it and keep growing as a person","nod"),
       ]),
      ("Full final practice of asking for forgiveness.",
       [("You hurt a friend by leaving them out of plans. Walk up to them. What do you say?",["excuse me","hey","can we talk","need to say","minute","sorry"],"Approach them","Hey I need to talk to you about something important","wave"),
        ("You say you are sorry. What specifically do you apologize for?",["left out","excluded","plans without","did not invite","sorry for","wrong"],"Name the specific act","I am sorry I made plans without including you that was wrong of me","sad"),
        ("They say they felt hurt. What do you say?",["understand","know","valid","right","makes sense","sorry for that","should not"],"Validate","I completely understand that must have really hurt and I am so sorry","sad"),
        ("You promise to do better. What do you say?",["include","invite","think of you","wont leave out","will make sure","change"],"Make a specific promise","I promise I will always include you and think of you when making plans","nod"),
        ("You ask for forgiveness. What do you say?",["forgive me","can you forgive","another chance","move on","fresh start","okay"],"Ask sincerely","Can you forgive me I truly value our friendship and I am sorry","sad"),
       ]),
     ]),
    # 24 forgive_friend
    ("forgive_friend","Forgiving a Friend","Practice accepting an apology and choosing to move forward.","💛","#FFF9C4","ff",
     "Excellent! You showed real maturity by accepting an apology and moving forward. You earned a star!",
     [
      ("Forgiving someone can be hard. Let us think about it.",
       [("What does forgiving someone mean?",["let go","move on","accept","not hold","okay","past","no longer angry"],"Say: letting go","Forgiving means letting go of the anger and choosing to move on","think"),
        ("Does forgiving mean you are okay with what happened?",["no","not mean","still happened","acknowledge","can forgive","still hurt"],"Say you can forgive but it still happened","No you can forgive someone while still acknowledging it hurt","think"),
        ("How does holding a grudge make you feel?",["bad","sad","angry","tired","stuck","heavy","hard","worse"],"Say it feels bad","Holding a grudge makes me feel heavy and stuck inside","sad"),
        ("What are the benefits of forgiving someone?",["feel better","move on","relief","lighter","peace","friendship","good"],"Name a benefit","Forgiving helps me feel lighter and at peace","nod"),
        ("Are you ready to practice accepting an apology?",["yes","ready","okay","sure","let us go","go ahead"],"Say yes","Yes I am ready to practice accepting an apology","nod"),
       ]),
      ("A friend is coming to apologize to you.",
       [("Your friend walks up and says sorry. What do you do first?",["listen","let them","hear them out","wait","okay","let speak"],"Listen first","I would listen and let them finish what they are saying","nod"),
        ("They apologize. Do you feel ready to respond?",["yes","kind of","little","not sure","okay","ready","think so"],"Check in with yourself","I think I am ready to respond calmly","nod"),
        ("They say they are really sorry. What do you say first?",["thank you","okay","heard you","appreciate","thanks for saying"],"Acknowledge the apology","Thank you for saying that I appreciate you coming to talk to me","nod"),
        ("They ask if you are okay. How do you answer honestly?",["little hurt","still","okay","getting there","better","was hard","hurt"],"Be honest","I was hurt but I am getting better and I appreciate the apology","sad"),
        ("They ask if you can forgive them. What do you say?",["yes","I forgive","okay","move on","fresh start","forgive you","willing"],"Accept","Yes I forgive you and I am willing to move forward","nod"),
       ]),
      ("What if you need more time?",
       [("You are not ready to forgive right now. What do you say?",["need time","not ready","little more","think","process","okay soon","working on it"],"Ask for time","I need a little more time but I am working on it","nod"),
        ("They say they understand. How do you respond?",["thank you","appreciate","means a lot","okay","glad","thank you for understanding"],"Say thanks","Thank you for understanding that means a lot to me","nod"),
        ("They ask if you will talk again soon. What do you say?",["yes","when ready","soon","hopefully","check in","not long"],"Say you will","Yes when I am ready I will reach out and talk again","nod"),
        ("Later you feel ready. How do you approach them?",["hey","can we talk","ready","wanted to say","okay now","forgive"],"Start the conversation","Hey I wanted to let you know I am ready to talk and I forgive you","wave"),
        ("They say thank you. How do you close the conversation?",["fresh start","move on","glad","okay now","past","together","good"],"Close it warmly","Let us put it behind us and have a fresh start together","nod"),
       ]),
      ("Let us talk about what forgiving looks like over time.",
       [("After forgiving do you have to be best friends again?",["no","not have to","can be","choice","decide","depends","up to you"],"Say it is your choice","No you can forgive someone without going back to how things were","think"),
        ("What does rebuilding trust look like?",["slowly","time","actions","consistent","show","little by little","small steps"],"Say it takes time","It happens slowly through consistent actions over time","think"),
        ("What if you feel angry again after forgiving?",["normal","okay","happens","acknowledge","talk","process","remind yourself"],"Say it is normal","It is normal sometimes to feel that way just remind yourself you chose to forgive","nod"),
        ("What helps you actually let go of the hurt?",["talk","time","breathe","writing","remind","focus forward","help","express"],"Name one thing","Talking about it and focusing on moving forward helps me let go","nod"),
        ("What would you tell a friend who is struggling to forgive?",["take time","okay","your pace","do not rush","when ready","support","here"],"Give advice","I would say take your time and do it when you feel ready I am here","nod"),
       ]),
      ("Practicing what to say during forgiveness.",
       [("A friend says: I messed up and I am sorry. What do you say?",["thank you","i hear you","appreciate","okay","heard"],"Acknowledge","Thank you for telling me I hear you and I appreciate that","nod"),
        ("They ask: Can we be okay again? What do you say?",["yes","I think so","willing","forgive","move on","fresh start","okay"],"Say yes","Yes I forgive you and I think we can be okay again","nod"),
        ("You still feel a little hurt. How do you express that kindly?",["still","little hurt","honest","but forgiving","wanted you to know","honest"],"Be honest kindly","I am still a little hurt but I am choosing to forgive you","sad"),
        ("They say they understand. What do you say next?",["move on","fresh start","glad we talked","okay now","behind us"],"Move forward","I am glad we talked let us move forward together","nod"),
        ("How do you both seal the reconciliation?",["good","shake","hug","okay","fresh start","all good","together"],"End positively","All good let us start fresh and move on from here","nod"),
       ]),
      ("Handling a repeated mistake after forgiving.",
       [("They did the same thing again. How do you feel?",["angry","frustrated","upset","hurt again","disappointed","betrayed","sad"],"Name your feeling","I feel frustrated and hurt that it happened again","sad"),
        ("What do you do before reacting?",["breathe","pause","calm","think","count","wait","do not react"],"Pause first","I would pause and take a breath before saying anything","nod"),
        ("You decide to talk to them again. What do you say?",["again","this happened again","need to talk","same thing","pattern","did it again"],"Address it calmly","I need to talk to you because this same thing has happened again","think"),
        ("They apologize again. Are you still willing to forgive?",["not sure","harder","need change","show me","maybe","actions","see","depends"],"Say it is harder","It is harder this time I need to see real change not just words","think"),
        ("What boundary do you set?",["if again","one more time","cannot continue","need to change","this is not okay"],"Set a clear boundary","If this happens again I may need to step back from this friendship","point"),
       ]),
      ("Role play: forgiving a sibling.",
       [("Your sibling borrowed something without asking. They apologize. What do you say first?",["thank you","appreciate","sorry for","okay","heard","thanks"],"Hear them out","Thank you for apologizing I appreciate that you came to me","nod"),
        ("They say they should have asked. Do you agree?",["yes","right","should have","next time","ask first","agree","correct"],"Agree","Yes you should have asked first next time please do that","point"),
        ("They promise not to do it again. What do you say?",["okay","trust you","hope so","believe you","mean it","we will see"],"Say you believe them","Okay I trust that you mean it and I forgive you","nod"),
        ("You want to make sure it does not happen again. What rule do you suggest?",["ask","permission","let me know","check with me","always ask first"],"Suggest a rule","Let us agree you will always ask before borrowing anything of mine","point"),
        ("They agree. How do you close the conversation?",["good","glad","okay now","thanks","all good","happy","move on"],"Close warmly","Good I am glad we sorted that out all good between us","nod"),
       ]),
      ("Final full practice: forgiving a classmate.",
       [("A classmate said something unkind about you. They apologize. What do you do first?",["listen","hear them","let them","okay","wait","let speak","stay calm"],"Listen calmly","I would listen calmly and let them finish apologizing","nod"),
        ("They say they are very sorry. What do you say?",["thank you","appreciate","heard","okay","acknowledge"],"Acknowledge","Thank you I appreciate you saying that to me","nod"),
        ("You tell them how it made you feel. What do you say?",["hurt","upset","embarrassed","bothered","affected","did not feel good","hard"],"Share the impact","What you said really hurt my feelings and made me feel embarrassed","sad"),
        ("They understand and ask if you can forgive them. What do you say?",["yes","forgive","okay","willing","move on","fresh start","I do"],"Forgive them","Yes I forgive you I do not want this between us","nod"),
        ("How do you close the conversation and move on?",["all good","fresh start","okay","glad","behind us","move forward","good"],"Move forward","All good let us move forward and put this behind us","nod"),
       ]),
     ]),
    # 25 try_new_thing
    ("try_new_thing","Trying Something New","Practice talking about nervousness and building courage to try new things.","🚀","#E8EAF6","tn",
     "You did it! You talked about your nervousness and found the courage to try something new! You earned a star!",
     [
      ("Trying something new can feel scary. Let us talk about it.",
       [("How does it feel to try something new?",["nervous","scared","excited","unsure","worried","butterflies","anxious"],"Say nervous or excited","I feel nervous but also a little excited when I try something new","think"),
        ("Why do people feel nervous about new things?",["unknown","not sure","might fail","unfamiliar","different","never done","new"],"Say: the unknown","People feel nervous because they do not know what to expect","think"),
        ("Is it okay to feel nervous?",["yes","normal","okay","allowed","everyone","fine","common"],"Say yes it is normal","Yes it is completely normal and everyone feels that way sometimes","nod"),
        ("What can nervousness actually mean?",["care","important","want to do well","matters","excited","good sign"],"Say it means it matters","It can mean you care about doing well which is a good sign","think"),
        ("What is one new thing you would like to try?",["sport","club","class","activity","friend","skill","art","music","cooking"],"Name something","I would like to try joining a club or learning a new skill","nod"),
       ]),
      ("Talking to someone about your nervousness.",
       [("You feel nervous about something new. Who do you tell?",["friend","parent","teacher","counselor","trusted","adult","someone"],"Name someone","I would tell a friend or a trusted adult how I feel","wave"),
        ("They ask what is making you nervous. What do you say?",["do not know what","never done","might fail","look silly","bad","wrong"],"Name your fear","I am nervous because I have never done it and I am afraid of failing","think"),
        ("They say: It is normal to be nervous. How do you respond?",["good to hear","helps","thank you","relieved","glad","okay"],"Accept reassurance","That is good to hear thank you it helps me feel better","nod"),
        ("They ask: What is the worst that could happen?",["fail","mess up","look silly","not good","people laugh","embarrass"],"Name your worry","I might fail or look silly in front of others","think"),
        ("They say: And what is the best that could happen?",["succeed","like it","good at","friend","fun","enjoy","proud"],"Name the best outcome","I could love it and be good at it and maybe make new friends","nod"),
       ]),
      ("Building courage to start.",
       [("You decide to try. What is your first step?",["sign up","ask","find out","look up","show up","go","start","first step"],"Name the first step","I would sign up or show up and see what it is about","point"),
        ("You feel scared at the door. What do you tell yourself?",["can do","try","okay","brave","just try","do my best","okay to fail","worth it"],"Encourage yourself","I tell myself I can do this and it is okay to just try my best","nod"),
        ("Someone new talks to you. What do you say?",["hi","hello","hey","my name","new here","first time","never done"],"Greet them","Hi I am new here this is my first time and I am a little nervous","wave"),
        ("They are friendly. How do you feel?",["better","relieved","good","okay","calmer","happy","glad","less nervous"],"Say you feel better","I feel better and less nervous knowing someone is friendly","nod"),
        ("You start the activity. It is hard at first. What do you say?",["okay","try","practice","learning","get better","first time","normal"],"Stay positive","It is my first time so it is okay that it is hard I will get better","nod"),
       ]),
      ("After trying the new thing.",
       [("How did it go overall?",["okay","fine","good","hard","fun","different","not bad","interesting","alright"],"Say how it went","It was hard at first but actually pretty interesting","nod"),
        ("What did you like about it?",["people","activity","learning","doing","challenge","trying","something different"],"Name one thing","I liked meeting new people and trying something different","nod"),
        ("What was the hardest part?",["start","beginning","knowing","not knowing","felt alone","nervous at first","not sure"],"Name the hardest part","The hardest part was getting started when I did not know anyone","think"),
        ("Would you try it again?",["yes","maybe","think so","want to","would like","give it","try again","open to"],"Answer","Yes I think I would give it another try","nod"),
        ("What would you tell someone else who is nervous to try it?",["just go","worth it","nervous okay","try","not as bad","okay","meet people"],"Give advice","I would say just go it is not as bad as you think and you might love it","nod"),
       ]),
      ("Talking about a specific fear.",
       [("You are nervous about joining a sports team. What worries you most?",["not good enough","other good","do not know anyone","fail","coach","team","cut"],"Name your worry","I worry I am not good enough and I do not know anyone on the team","think"),
        ("A friend says everyone was new once. What do you say?",["true","good point","right","never thought","helps","thanks","comforting"],"Accept the point","That is true and a good point I had not thought of it that way","nod"),
        ("You go to the first practice. Someone asks your name. What do you say?",["my name","i am","name is","hi","hello","new here"],"Introduce yourself","Hi my name is Alex and this is my first practice","wave"),
        ("Coach says welcome. How do you respond?",["thank you","thanks","glad","happy","excited","nervous but","ready"],"Respond","Thank you I am nervous but I am excited to learn","nod"),
        ("After practice how do you feel?",["good","proud","tired","better","glad","did it","happy","relieved"],"Say how you feel","I feel really proud of myself for showing up and giving it a try","nod"),
       ]),
      ("What to say when you want to quit.",
       [("You tried the new thing and want to give up. Who do you tell?",["parent","friend","coach","teacher","adult","someone","trust"],"Tell someone","I would tell my parent or coach how I am feeling","wave"),
        ("You say: I want to quit. What reason do you give?",["hard","not good","do not like","scared","tired","not working","struggled"],"Give a reason","It is too hard and I feel like I am not getting any better","sad"),
        ("They say: Give it one more try. How do you respond?",["okay","one more","fine","will try","alright","one chance","maybe"],"Give it one more try","Okay I will give it one more try before deciding","nod"),
        ("You try once more and do better. What do you say?",["surprised","better","glad","kept going","did not expect","wow","improved"],"Acknowledge the improvement","I am surprised I actually did better I am glad I kept going","nod"),
        ("Looking back was it worth sticking with it?",["yes","glad","worth it","learned","improved","tried","grew","good decision"],"Say yes","Yes I am glad I stayed it was worth pushing through","nod"),
       ]),
      ("Talking to yourself to build courage.",
       [("Before trying something scary what can you say to yourself?",["can do","brave","just try","worth trying","okay","do my best","go for it"],"Name a phrase","I can tell myself: you can do this just give it a try","nod"),
        ("What does it mean to be brave?",["do it anyway","scared but go","try even scared","face fear","move forward","despite nervous"],"Say brave means trying despite fear","Being brave means doing it even when you are scared","think"),
        ("Name one person who is brave that you admire.",["parent","friend","athlete","teacher","character","role model","someone"],"Name someone","I admire my parent they are brave and try new things all the time","nod"),
        ("What do you say after you try something scary?",["did it","proud","survived","made it","not bad","okay","brave","yes"],"Say something proud","I did it I am really proud of myself for trying","nod"),
        ("What new thing will you try next?",["activity","club","class","sport","skill","hobby","cooking","music","art"],"Name something","I want to try a cooking class or a new sport next","nod"),
       ]),
      ("Final full practice: trying a new activity.",
       [("You are about to try something new for the first time. How do you feel?",["nervous","excited","both","scared","butterflies","unsure","little afraid"],"Name your feeling","I feel nervous and excited at the same time I have butterflies","think"),
        ("You arrive and see other people. What do you say to someone?",["hi","hey","my name","first time","new here","hello","never done"],"Introduce yourself","Hi I am new here this is my first time trying this","wave"),
        ("They welcome you. How do you respond?",["thank you","glad","happy","appreciate","nice","good to be here","thanks"],"Respond warmly","Thank you I am nervous but glad to be here","nod"),
        ("It is your turn to try. You feel scared. What do you tell yourself?",["can do","okay","just try","brave","do my best","here goes","let us go"],"Encourage yourself","Here goes I can do this let us just give it my best try","nod"),
        ("Afterward how do you feel about trying something new?",["proud","glad","better","relieved","worth it","happy I tried","good","brave"],"Say you are proud","I feel proud and glad I tried it was totally worth it","nod"),
       ]),
     ]),
    # 26 at_store
    ("at_store","Buying Something at a Store","Practice finding items, paying, and being polite with store staff.","🛒","#F3E5F5","st",
     "Great job! You found what you needed, paid politely, and thanked the staff. Real-world skills! You earned a star!",
     [
      ("Let us practice shopping at a store.",
       [("Why is it helpful to know what you want before shopping?",["saves time","faster","easier","know what","prepared","list","organized"],"Say it saves time","Knowing what you want saves time and makes shopping easier","think"),
        ("What do you do first when you enter a store?",["look around","find","locate","check","ask","map","section","area"],"Say you look for what you need","I would look around to find the section I need","nod"),
        ("You cannot find the item. Who do you ask?",["staff","employee","worker","person","clerk","assistant","someone working"],"Say you ask a staff member","I would find a staff member and ask for help","wave"),
        ("How do you get a staff member attention politely?",["excuse me","hi","sorry to bother","hey","pardon","could you help"],"Say excuse me","I would say excuse me politely to get their attention","wave"),
        ("Ready to practice?",["yes","ready","okay","sure","let us go","go ahead"],"Say yes","Yes I am ready to practice buying something","nod"),
       ]),
      ("Asking a staff member for help.",
       [("You walk up to a staff member. What do you say?",["excuse me","hi","could you help","looking for","need help","find"],"Start with excuse me","Excuse me could you please help me find something","wave"),
        ("They say sure. How do you describe what you want?",["looking for","need","want to buy","find","item","product","name it"],"Describe the item","I am looking for a notebook do you know where I can find one","think"),
        ("They say aisle five. How do you respond?",["thank you","thanks","appreciate","great","helpful","perfect"],"Say thank you","Thank you so much that is really helpful","nod"),
        ("You go to aisle five but cannot find the right one. What do you do?",["go back","ask again","look harder","try another","ask different","excuse me again"],"Ask again","I would go back and ask the staff member for a bit more help","wave"),
        ("They come and show you. What do you say?",["thank you","thanks","perfect","found it","appreciate","great"],"Thank them","Thank you so much you found it right away I appreciate your help","nod"),
       ]),
      ("Checking the price and deciding.",
       [("You look at the price. It is more than you expected. What do you say to yourself?",["too much","can afford","check","think","budget","over","should","worth it"],"Think it through","I should check if this is within my budget before buying it","think"),
        ("You decide to ask if there is a cheaper option. What do you say?",["cheaper","less expensive","budget","another option","different price","lower","similar"],"Ask for alternatives","Excuse me do you have a similar item that is a bit less expensive","wave"),
        ("They show you two options. How do you decide?",["compare","price","quality","need","which","better","use","purpose"],"Compare the options","I would compare the price and decide which one fits my need better","think"),
        ("You choose one. What do you say?",["this one","i will take","decided","going with","choose this","this is good"],"Tell them your choice","I will go with this one thank you for showing me the options","nod"),
        ("They say good choice. How do you respond?",["thanks","thank you","appreciate","glad","good","perfect","okay"],"Thank them","Thank you I think it will work well for me","nod"),
       ]),
      ("Going to the checkout.",
       [("You bring your item to the checkout. What do you say to the cashier?",["hi","hello","hey","good morning","afternoon","how are you","hi there"],"Greet the cashier","Hi there how are you doing today","wave"),
        ("They ask if you found everything okay. What do you say?",["yes","i did","found it","with help","all good","everything fine","staff helped"],"Answer","Yes I found everything fine thank you a staff member was really helpful","nod"),
        ("They tell you the total. What do you say or do?",["here","pay","card","cash","okay","sure","ready","hand over"],"Pay","Here you go and thank you","nod"),
        ("They give you your change or receipt. What do you say?",["thank you","thanks","appreciate","have a good","goodbye"],"Say thank you","Thank you and have a great day","wave"),
        ("They say thanks come again. How do you respond?",["will do","thanks","you too","for sure","thank you","take care"],"Respond warmly","Thank you I will take care","wave"),
       ]),
      ("What if something is wrong with the item?",
       [("You get home and the item is damaged. What is your first step?",["go back","return","check receipt","find receipt","call","contact","store"],"Keep the receipt and go back","I would keep my receipt and go back to the store to return it","point"),
        ("You arrive at the store and go to the service desk. What do you say?",["excuse me","bought","problem","damaged","broken","issue","want to return","faulty"],"Explain the problem","Excuse me I bought this yesterday and it was damaged when I opened it","sad"),
        ("They ask if you have the receipt. What do you say?",["yes","here","have it","brought it","receipt here","got it"],"Say yes","Yes I have the receipt right here","nod"),
        ("They offer to exchange it. What do you say?",["yes please","exchange","new one","thank you","great","appreciate","yes"],"Accept","Yes please an exchange would be great thank you","nod"),
        ("They hand you a new one. How do you close the interaction?",["thank you","thanks","appreciate","helpful","have a good","goodbye"],"Say thank you and goodbye","Thank you so much for sorting that out have a great day","wave"),
       ]),
      ("Buying something with a budget.",
       [("You have ten dollars to spend. What do you do first?",["check prices","look","budget","how much","what can","afford","plan"],"Check prices first","I would check prices first and see what I can afford with ten dollars","think"),
        ("An item costs twelve dollars. What do you do?",["too much","over","cannot","look for","cheaper","different","pass"],"Look for something cheaper","That is over my budget so I would look for something less expensive","think"),
        ("You find something for eight dollars. What do you say?",["this works","within budget","good price","can afford","choose this","this one"],"Choose it","This works it is within my budget and I can pay for it","nod"),
        ("At checkout the total with tax is nine dollars. What do you do?",["pay","hand over","okay","have enough","here","still good","fine"],"Pay","I would hand over my money and I still have enough with the tax","nod"),
        ("You have one dollar left. What might you say?",["good","left over","saved","okay","kept change","have change","did not spend all"],"Acknowledge the change","I stayed within budget and have a dollar left which is good","nod"),
       ]),
      ("Practicing good store manners.",
       [("What should you NOT do in a store?",["run","yell","touch everything","be loud","mess up","throw","disturb","break"],"Name one thing","I should not run or be loud and disturb other shoppers","nod"),
        ("What if you accidentally knock something off the shelf?",["pick up","sorry","put back","apologize","staff","tell someone","fix"],"Pick it up","I would pick it up and put it back or tell a staff member","nod"),
        ("A very long line forms at checkout. What do you do?",["wait","patient","okay","not rush","stand","quietly","my turn","respect"],"Wait patiently","I would wait patiently in line and respect others in the queue","nod"),
        ("Someone lets you go ahead because you have fewer items. What do you say?",["thank you","thanks","appreciate","kind","nice","very kind","grateful"],"Thank them","Thank you that is very kind of you","nod"),
        ("You leave the store. What is one last polite thing to do?",["thank","goodbye","hold door","smile","nod","wave","have a good day"],"Say goodbye","I would say thank you or have a nice day to the staff on the way out","wave"),
       ]),
      ("Full practice: a complete shopping trip.",
       [("You enter the store. A greeter says hello. What do you say?",["hi","hello","hey","good","how are you","afternoon","morning","thanks"],"Greet back","Hi there thank you good to be here","wave"),
        ("You need help finding shampoo. What do you say to staff?",["excuse me","help","find","looking for","shampoo","where","aisle"],"Ask politely","Excuse me I am looking for shampoo could you tell me where it is","wave"),
        ("Staff points you to aisle three. What do you say?",["thank you","thanks","perfect","great","appreciate","helpful"],"Thank them","Thank you so much that is really helpful","nod"),
        ("You choose one and go to checkout. Cashier greets you. What do you say?",["hi","hello","hey","good","fine","how are you","doing well"],"Greet the cashier","Hi how are you doing today","wave"),
        ("They give you your total. You pay and get a receipt. What do you say before leaving?",["thank you","thanks","have a good","goodbye","take care","nice day","appreciate"],"Say goodbye","Thank you have a wonderful rest of your day goodbye","wave"),
       ]),
     ]),
    # 27 at_doctor
    ("at_doctor","At the Doctor","Practice checking in, describing symptoms, and understanding the treatment plan.","🩺","#E0F2F1","dr",
     "Excellent! You checked in, explained your symptoms, and understood your care plan. Real confidence! You earned a star!",
     [
      ("Let us practice going to the doctor.",
       [("Why is it important to be able to talk to a doctor?",["health","care","help","symptoms","need","tell","know","important","feel better"],"Say: to get proper help","So the doctor can understand how I feel and help me get better","think"),
        ("What should you tell the doctor when you arrive?",["name","appointment","here for","check up","sick","symptoms","reason"],"Say your name and why you are there","I should give my name and explain why I came to see the doctor","think"),
        ("What is a symptom?",["sign","feeling","what you feel","pain","ache","sore","how body feels","problem"],"Say: signs of how you feel","A symptom is a sign your body gives to show something is wrong","think"),
        ("Can you name two symptoms?",["headache","fever","cough","pain","sore","tired","nausea","stomachache","dizzy"],"Name two","I might have a headache and a fever for example","think"),
        ("Ready to practice talking to a doctor?",["yes","ready","okay","sure","let us","go","think so"],"Say yes","Yes I feel ready to practice talking to a doctor","nod"),
       ]),
      ("Checking in at the reception desk.",
       [("You walk in and approach the desk. What do you say?",["hi","hello","checking in","appointment","name","here to see","good morning"],"Check in","Hi I have an appointment my name is Alex","wave"),
        ("They ask for your date of birth. What do you say?",["birthday","date of birth","born","my birthday is","january","february","year","tell them"],"Give your birthday","My date of birth is March 5 2010","nod"),
        ("They ask for your insurance card. What do you say?",["here","have it","card","give","brought","yes","hand over"],"Hand it over","Here is my insurance card thank you","nod"),
        ("They tell you to have a seat. What do you say?",["thank you","okay","sure","will do","alright","seat","right away"],"Respond politely","Thank you I will take a seat right over here","nod"),
        ("You wait and they call your name. You say?",["here","that is me","coming","yes","ready"],"Respond when called","That is me I am coming thank you","nod"),
       ]),
      ("The nurse takes your vitals.",
       [("The nurse asks: How are you today? What do you say?",["not great","not feeling well","okay","fine","little sick","been better","not good"],"Answer honestly","I have not been feeling well that is why I am here","sad"),
        ("They take your temperature. It is high. They ask how long you have had a fever. What do you say?",["few days","since yesterday","day","two days","started","this week","began"],"Give a timeframe","I have had a fever for about two days now","sad"),
        ("They ask what other symptoms you have. What do you say?",["headache","cough","tired","sore throat","aches","pain","stomach","nausea"],"Name your symptoms","I also have a headache and I feel really tired and achy","sad"),
        ("They ask how bad your pain is on a scale of one to ten. What do you say?",["six","seven","five","eight","bad","pretty bad","moderate","hurts a lot","four"],"Give a number","I would say about a six or seven it is pretty uncomfortable","sad"),
        ("They say the doctor will be in shortly. What do you say?",["thank you","okay","appreciate","will wait","good","sure"],"Say thank you","Thank you I will wait right here","nod"),
       ]),
      ("Talking to the doctor.",
       [("The doctor walks in and greets you. What do you say?",["hi","hello","how are","good","thanks for seeing","morning","afternoon"],"Greet them","Hi thank you for seeing me today doctor","wave"),
        ("They ask what brings you in. What do you say?",["not feeling well","sick","fever","symptoms","cough","headache","few days","been sick"],"Explain why you are there","I have been sick for a few days I have a fever headache and I feel very tired","sad"),
        ("They ask if anyone at home is also sick. What do you say?",["no","yes","not sure","my sibling","parent","no one","alone","just me"],"Answer","Not that I know of it seems to just be me right now","nod"),
        ("They ask if you have any allergies to medication. What do you say?",["no","yes","not that I know","allergic to","no allergies","one allergy","penicillin"],"Answer honestly","No I do not have any known medication allergies","nod"),
        ("They ask you to describe the pain in your throat. What do you say?",["sore","scratchy","hurts to swallow","dry","burning","swollen","painful"],"Describe it","It feels sore and it hurts when I swallow it is quite painful","sad"),
       ]),
      ("Understanding the diagnosis and plan.",
       [("The doctor says you have a throat infection. Do you understand what that means?",["yes","kind of","not really","what does","tell me more","understand","explain"],"Ask or confirm","Yes I think I understand but could you explain a little more","think"),
        ("They say they are prescribing antibiotics. Do you know what to ask?",["how often","how many days","with food","side effects","take","instructions","when"],"Ask how to take it","How often do I take them and should I take them with food","think"),
        ("They say twice a day for seven days. What do you say?",["okay","understood","will do","got it","seven days","morning night","twice","sure"],"Confirm","Okay twice a day for seven days I understand","nod"),
        ("They say finish the full course even if you feel better. Why is that important?",["kill all","get better fully","come back","resist","all germs","done fighting","effective","important"],"Explain","Because stopping early might leave some bacteria behind and they could come back stronger","think"),
        ("They ask if you have questions. What do you say?",["no","one question","what about","when better","yes","okay","clarify"],"Ask or say you are good","Just one question how long before I start feeling better","think"),
       ]),
      ("Asking about your care at home.",
       [("Doctor says rest and drink fluids. Can you repeat back what they said?",["rest","drink fluids","water","lots of","plenty","stay home","sleep"],"Repeat the instructions","Rest at home and drink plenty of fluids like water and juice","nod"),
        ("They say no school for two days. What do you say?",["okay","understood","two days","will tell","parent knows","alright","sure"],"Confirm","Okay two days at home I will let my parent know","nod"),
        ("They say come back if symptoms get worse. What does that mean to you?",["more sick","worse","high fever","cannot breathe","really bad","emergency","worse not better"],"Explain in your own words","If I feel much worse or my fever goes really high I should come back","think"),
        ("They ask if you need anything else. What do you say?",["no","i think","okay","that is all","nothing more","good for now","thank you"],"Say you are good","I think I have everything I need thank you doctor","nod"),
        ("They say feel better soon. What do you say?",["thank you","thanks","appreciate","will try","hope so","grateful","kind"],"Say thank you","Thank you so much I appreciate your help doctor","wave"),
       ]),
      ("Picking up medication at the pharmacy.",
       [("You go to the pharmacy with your prescription. What do you say at the counter?",["hi","hello","prescription","pick up","dropping off","have a script","name"],"Check in","Hi I have a prescription I would like to drop off or pick up please","wave"),
        ("They ask for your name and date of birth. What do you say?",["name is","my name","birthday","date of birth","tell them","give info"],"Give your info","My name is Alex and my date of birth is March 5 2010","nod"),
        ("They say it will be ready in fifteen minutes. What do you say?",["okay","no problem","will wait","right back","sure","take my time","fine"],"Say okay","Okay I will wait right here thank you","nod"),
        ("They call your name and hand you the bag. What do you ask before leaving?",["instructions","how to take","side effects","anything I should know","with food","any warnings"],"Ask for instructions","Is there anything I should know about taking this medication","think"),
        ("They say take with food twice a day. How do you respond?",["okay","understood","got it","will do","twice a day food","sure","thank you"],"Confirm and thank them","Understood twice a day with food thank you so much","nod"),
       ]),
      ("Full final practice: a complete doctor visit.",
       [("You arrive at the clinic and walk to the desk. What do you say?",["hi","hello","appointment","checking in","here to see","my name","good morning"],"Check in","Hi I have an appointment my name is Alex and I am here to see the doctor","wave"),
        ("Nurse asks your symptoms. What do you say?",["fever","headache","tired","cough","sore throat","few days","not well","sick","aches"],"Describe your symptoms","I have had a fever a headache and a sore throat for about three days now","sad"),
        ("Doctor asks how bad the pain is. What do you say?",["scale","number","six","seven","five","bad","hurts","uncomfortable","painful"],"Give a rating","I would say about a six it is uncomfortable but I can still talk and move","sad"),
        ("Doctor gives you a prescription. What do you ask?",["how to take","how often","days","side effects","food","instructions","anything to know"],"Ask questions","How often should I take it and are there any side effects I should know about","think"),
        ("Doctor says feel better. How do you close the visit?",["thank you","thanks","appreciate","helpful","feel better","goodbye","take care"],"Thank them and say goodbye","Thank you so much doctor I really appreciate your help goodbye","wave"),
       ]),
     ]),
    # 28 on_phone
    ("on_phone","Making a Phone Call","Practice introducing yourself on a call, stating your purpose, and saying goodbye.","📞","#FFF3E0","ph",
     "Well done! You made a complete phone call — hello, your reason for calling, and a polite goodbye! You earned a star!",
     [
      ("Making a phone call can feel awkward. Let us practice.",
       [("When do you need to make a phone call?",["appointment","ask","information","remind","confirm","contact","reach","business"],"Name a reason","I might call to confirm an appointment or get information","think"),
        ("What should you have ready before calling?",["know what","number","purpose","name","what to say","write","notes","prepared"],"Say you should know your purpose","I should know what I want to say and have the number ready","think"),
        ("How do you start a phone call politely?",["hello","hi","my name","calling because","this is","good morning","afternoon"],"Say hello and give your name","I would say hello my name is Alex and explain why I am calling","wave"),
        ("What should you do if the person is not available?",["leave message","call back","voicemail","try again","ask someone","note","name number"],"Say leave a message","I would leave a message with my name and a phone number to call back","think"),
        ("Ready to practice making a phone call?",["yes","ready","okay","sure","go ahead","let us"],"Say yes","Yes I am ready to practice making a phone call","nod"),
       ]),
      ("Calling to make an appointment.",
       [("Phone rings and someone answers: Good morning, how can I help you? What do you say?",["hello","hi","my name","calling","appointment","would like","schedule","book"],"State your purpose","Hello my name is Alex and I would like to schedule an appointment please","wave"),
        ("They ask what the appointment is for. What do you say?",["checkup","doctor","dentist","haircut","annual","reason","visit","routine","follow up"],"Explain the reason","It is for a routine checkup with the doctor","think"),
        ("They ask what days work for you. What do you say?",["monday","tuesday","weekend","afternoon","morning","anytime","flexible","available","prefer"],"Give your availability","I am free most afternoons this week or anytime on Saturday","nod"),
        ("They offer Tuesday at 2pm. What do you say?",["yes","that works","perfect","sounds good","okay","tuesday works","confirm","great"],"Confirm","Yes Tuesday at two pm works perfectly for me thank you","nod"),
        ("They say they will send a reminder. What do you say before hanging up?",["thank you","thanks","great","appreciate","goodbye","see you then","look forward"],"Say thanks and goodbye","Thank you so much I appreciate it I will see you then goodbye","wave"),
       ]),
      ("Leaving a voicemail.",
       [("No one answers and you get voicemail. What do you say first?",["hi","hello","my name","this is","calling for"],"Start with your name","Hi my name is Alex and I am calling for Doctor Smith's office","wave"),
        ("What do you say next to explain why you are calling?",["calling about","appointment","question","wanted to ask","reason","need","following up"],"State your reason","I am calling because I would like to schedule an appointment for a checkup","think"),
        ("What information do you leave so they can call back?",["number","phone","reach me","call back","best time","available","name number"],"Leave your contact info","My phone number is 555 1234 and I am available after 3pm on weekdays","point"),
        ("How do you end the voicemail?",["thank you","please call back","look forward","goodbye","appreciate","when you can","soon"],"Close the message","Thank you please call me back when you get a chance I appreciate it","wave"),
        ("What would you do if they do not call back in a day or two?",["call again","try again","reach out","follow up","patient","check","call back"],"Say you would try again","I would wait a day or two and then call back to follow up","think"),
       ]),
      ("Handling an unexpected answer.",
       [("You call but a different person answers. What do you say?",["hi","hello","speaking with","right number","who is","wanted to reach","is this"],"Check you have the right person","Hi is this the right number for the doctor office I am looking for","wave"),
        ("They say yes. What do you say next?",["great","good","okay then","continue","my name","calling because","so glad"],"Continue the call","Great my name is Alex and I am calling to make an appointment","wave"),
        ("They say the person you want is not in. What do you ask?",["when back","call back","message","leave","available","return","reach"],"Ask what to do","Could I leave a message or is there a better time to call back","think"),
        ("They say to call back tomorrow morning. What do you say?",["okay","will do","thank you","morning","tomorrow","noted","appreciate","sure"],"Confirm","Okay I will call back tomorrow morning thank you for letting me know","nod"),
        ("You call back and get through. What do you say?",["hi","hello","called yesterday","following up","wanted to reach","my name","mentioned calling back"],"Reference the earlier call","Hi I called yesterday and was told to try back this morning my name is Alex","wave"),
       ]),
      ("Ending a phone call properly.",
       [("The conversation is done. How do you signal you are wrapping up?",["well","thanks","i think","that is all","okay then","covered","think that is it"],"Signal the end","Well I think that covers everything thank you so much","nod"),
        ("They say goodbye first. What do you say?",["goodbye","bye","take care","thanks","have a good","bye bye","see you","appreciate"],"Respond","Goodbye and thank you have a wonderful day","wave"),
        ("You need to end the call but they keep talking. What do you say?",["sorry","need to go","have to run","quickly","one last thing","wrap up","shortly"],"End politely","I am so sorry to interrupt but I need to go soon is there anything else you need","nod"),
        ("They say no. What is your final line?",["great","perfect","okay","goodbye then","talk soon","appreciate","take care","bye"],"Close the call","Perfect well goodbye then and thank you for your help","wave"),
        ("After hanging up what might you do?",["write down","note","calendar","confirm","remember","record","put in phone","remind"],"Note any important info","I would write down any important information like the appointment time","point"),
       ]),
      ("Calling a friend.",
       [("You call a friend. They answer. What do you say?",["hey","hi","it is me","my name","what is up","how are","long time","calling to"],"Greet them","Hey it is Alex how are you doing","wave"),
        ("They say hi and ask how you are. What do you say?",["good","fine","great","okay","not bad","pretty good","doing well","alright"],"Answer","I am doing pretty good thank you for asking","nod"),
        ("You want to invite them somewhere. What do you say?",["wanted to ask","see if","free","this weekend","hang out","plans","come","want to"],"Make the invite","I wanted to see if you are free this weekend to hang out","wave"),
        ("They say yes. What details do you share?",["where","when","time","place","meet","address","what time","plan","how","details"],"Give the details","I was thinking we could meet at the park on Saturday at two pm","think"),
        ("They agree. How do you end the call?",["great","perfect","see you","bye","talk later","Saturday","goodbye","look forward"],"Say bye","Great I am really looking forward to it see you Saturday bye","wave"),
       ]),
      ("Calling for information.",
       [("You call a store to check if they have an item. What do you say first?",["hi","hello","calling to check","have","stock","item","wondering","question"],"State your question","Hi I am calling to ask if you currently have a certain item in stock","wave"),
        ("They ask which item. What do you say?",["looking for","specific","name","want to know","looking for","it is called","type","kind"],"Name the item","I am looking for a blue backpack in a medium size","think"),
        ("They say yes they have it. What do you ask next?",["price","how much","cost","available","reserve","hold","buy","quantity"],"Ask the price or about holding","Could you tell me the price and is it possible to hold one for me","think"),
        ("They say yes they can hold it. What do you say?",["great","thank you","name","give","for how long","appreciate","yes","confirm"],"Confirm the hold","Thank you my name is Alex please hold it under that name","nod"),
        ("They say it is held for 24 hours. What do you say before hanging up?",["thank you","great","perfect","coming in","tomorrow","appreciate","bye","will be there"],"Thank them and say goodbye","Thank you I will come in today or tomorrow goodbye","wave"),
       ]),
      ("Full final phone call practice.",
       [("Phone rings. Someone answers: Hello how can I help? What do you say?",["hi","hello","my name","calling about","reason","would like","this is","question"],"State your name and reason","Hello my name is Alex and I am calling to schedule a dentist appointment please","wave"),
        ("They ask your preferred days. What do you say?",["tuesday","thursday","anytime","afternoon","morning","weekend","flexible","free","available"],"Give your availability","I am free Tuesday or Thursday afternoons or anytime Saturday morning","nod"),
        ("They offer Thursday at 10am. What do you say?",["yes","that works","perfect","sounds good","great","confirm","thursday ten"],"Confirm","Yes Thursday at ten am sounds perfect thank you","nod"),
        ("They ask for your phone number for the reminder. What do you say?",["number","phone","555","give","here it is","it is","reach me"],"Give your number","My phone number is 555 9876 thank you","nod"),
        ("They say see you Thursday. What do you say before hanging up?",["thank you","see you","goodbye","look forward","appreciate","take care","bye"],"Say goodbye","Thank you so much I look forward to it goodbye","wave"),
       ]),
     ]),
    # 29 at_dentist
    ("at_dentist","At the Dentist","Practice checking in, describing discomfort, and asking questions.","🦷","#E8F5E9","de",
     "Fantastic! You handled a dentist visit like a pro — checked in, described your feelings, and asked great questions! You earned a star!",
     [
      ("Let us talk about going to the dentist.",
       [("Why is it important to go to the dentist regularly?",["teeth","clean","healthy","cavity","check","prevent","care","oral","brush"],"Say: to keep teeth healthy","Going regularly helps keep my teeth healthy and prevents problems","think"),
        ("How often should most people go to the dentist?",["twice a year","every six months","once a year","two times","regular","often","routine"],"Say twice a year","Most people should go about twice a year for checkups","think"),
        ("What are common things a dentist checks?",["teeth","gums","cavity","x ray","bite","clean","check","look","health"],"Name two things","They usually check for cavities and clean my teeth and look at my gums","think"),
        ("How do you feel about going to the dentist?",["nervous","okay","fine","scared","anxious","not bad","okay with it","little worried"],"Say how you feel","I feel a little nervous but I know it is important for my health","nod"),
        ("Ready to practice talking at the dentist?",["yes","ready","okay","sure","let us","go ahead"],"Say yes","Yes I am ready to practice the dentist conversation","nod"),
       ]),
      ("Checking in at the dental office.",
       [("You enter and go to the front desk. What do you say?",["hi","hello","appointment","checking in","my name","here for","good morning"],"Check in","Hi I have an appointment my name is Alex","wave"),
        ("They ask if you filled out the forms. What do you say?",["yes","here","form","filled","completed","brought","signed"],"Answer","Yes I already filled them out here they are","nod"),
        ("They ask if your contact info is still the same. What do you say?",["yes","same","has not changed","still correct","all good","still the same","no changes"],"Confirm","Yes everything is still the same no changes","nod"),
        ("They ask you to have a seat. What do you say?",["okay","thank you","will do","sure","be right here","alright","heading over"],"Respond","Okay thank you I will be right over there","nod"),
        ("The dental assistant calls your name. What do you say?",["here","that is me","yes","coming","ready","on my way"],"Respond","Yes that is me I am coming thank you","nod"),
       ]),
      ("Talking to the dental assistant.",
       [("They ask how your teeth have been. What do you say?",["fine","okay","little pain","sensitive","one spot","bothering","noticed something","been okay"],"Answer honestly","They have been mostly okay but one spot has been a little sensitive","sad"),
        ("They ask where it hurts. What do you say?",["back","top","bottom","left","right","molar","front","side","here","this one"],"Point and describe","It is on the lower right side near the back tooth","sad"),
        ("They ask how long it has been sensitive. What do you say?",["week","few days","month","while","recently","lately","since","started","this week"],"Give a timeframe","It started about a week ago and has been bothering me since","sad"),
        ("They ask if anything makes it worse. What do you say?",["cold","hot","sweet","biting","pressure","sugar","drink","eat","touch"],"Describe triggers","Cold drinks and sweet things seem to make it worse","sad"),
        ("They say the dentist will check it. What do you say?",["okay","good","thank you","glad","yes","hope they find","hopefully"],"Say okay","Okay good I am glad they will take a look at it","nod"),
       ]),
      ("During the checkup with the dentist.",
       [("The dentist says hello. What do you say?",["hi","hello","good","how are","morning","afternoon","thanks for seeing"],"Greet them","Hi thank you for seeing me today","wave"),
        ("They look at your teeth and say open wide. What do you do?",["open mouth","open","say ah","okay","ready","wide","yes","open up"],"Follow the instruction","I would open my mouth wide as they asked","nod"),
        ("They say they found a small cavity. Do you understand?",["yes","kind of","what does","what is","explain","okay","i see","tell me more"],"Say you understand or ask to explain","I understand but could you explain what a cavity means and what happens next","think"),
        ("They say they will fill it. You are a little scared. What do you say?",["okay","nervous","scared","little worried","will it hurt","does it hurt","what will"],"Ask about the procedure","Okay I am a little nervous will it hurt much","think"),
        ("They say it will be quick and not painful. How do you respond?",["okay","relieved","good to hear","thank you","feel better","glad","okay then"],"Express relief","Okay that is good to hear I feel better knowing that thank you","nod"),
       ]),
      ("After the procedure.",
       [("The procedure is done. They say you did great. What do you say?",["thank you","glad","relieved","over","done","feel okay","good","whew","appreciate"],"Respond","Thank you I am really glad it is over and that it went well","nod"),
        ("They tell you to avoid certain foods for a few hours. What do you ask?",["which foods","what not to eat","hot cold","restrictions","avoid","careful","eat","drink"],"Ask what to avoid","Which foods or drinks should I avoid and for how long","think"),
        ("They say avoid hot food for two hours. What do you say?",["okay","got it","understood","will do","two hours","sure","alright","no hot food"],"Confirm","Okay I will avoid hot food for two hours I understand","nod"),
        ("They ask if you have any questions before leaving. What do you say?",["just one","yes","quick question","one thing","how do I","do I","should I","will I","anything else"],"Ask one question","Just one thing how often should I floss and are there any other tips","think"),
        ("They give advice. How do you end the visit?",["thank you","see you","goodbye","next appointment","when is","six months","appreciate","bye"],"Close politely","Thank you so much I will see you in six months goodbye","wave"),
       ]),
      ("Talking about fear at the dentist.",
       [("Before the visit you feel really scared. What can you do?",["breathe","tell someone","talk","prepare","know what","ask ahead","remind self","okay"],"Name one strategy","I can take deep breaths and remind myself it will be quick and painless","nod"),
        ("You tell the dentist you are scared. What do you say?",["nervous","scared","anxious","afraid","worried","tell you","just wanted","let you know"],"Be honest","I just wanted to let you know I feel a bit nervous about this","think"),
        ("They say they will be gentle. How do you respond?",["thank you","appreciate","feel better","helps","okay","good to know","relieved","glad"],"Say thank you","Thank you that helps a lot I feel a little better now","nod"),
        ("You ask them to stop if you raise your hand. What do you say?",["raise hand","signal","stop","need break","pause","tell you","give sign","uncomfortable"],"Ask for a signal","Could we agree that if I raise my hand you will pause for a moment","think"),
        ("They agree. How do you feel now?",["better","relieved","good","safer","okay","calmer","less scared","more comfortable"],"Say you feel better","I feel much more comfortable now knowing I have a way to signal","nod"),
       ]),
      ("Asking about dental care at home.",
       [("They ask how often you brush. What do you say?",["twice","two times","morning night","every day","twice daily","usually","most days"],"Answer","I brush twice a day morning and night","nod"),
        ("They ask if you floss. What do you say?",["sometimes","daily","every day","not always","try to","usually","a few times","could do more"],"Answer honestly","I floss sometimes but I know I should do it more consistently","nod"),
        ("They suggest using fluoride toothpaste. Do you use it?",["yes","think so","believe so","check","not sure","use","yes I do","always"],"Answer","I think so I usually buy the one recommended for teens","nod"),
        ("They say to rinse with mouthwash. Do you have any questions?",["when to rinse","which type","before after","morning night","how long","which one","type"],"Ask a question","Should I use mouthwash before or after brushing and is there a specific type","think"),
        ("They explain and you are ready to go. What do you say?",["thank you","got it","understood","really helpful","will do","try that","appreciate","good advice"],"Close the visit","Thank you that was really helpful I will definitely follow those tips goodbye","wave"),
       ]),
      ("Full final practice: a complete dentist visit.",
       [("You walk in and check in. What do you say at the desk?",["hi","hello","appointment","my name","checking in","here for","have an appointment"],"Check in","Hi I have an appointment my name is Alex checking in please","wave"),
        ("Nurse asks how your teeth have been. What do you say?",["fine","one spot","sensitive","little pain","bothering me","okay except","noticed","mostly good"],"Describe your experience","Mostly fine but I have noticed one sensitive spot on my lower right side","sad"),
        ("Dentist says they will check it. You feel nervous. What do you say?",["little nervous","scared","anxious","will it hurt","does it","okay but","nervous about"],"Say how you feel","I am a little nervous could you tell me what to expect","think"),
        ("Dentist says it is routine. How do you respond?",["okay","good to know","feel better","thank you","relieved","appreciate","glad"],"Express relief","Okay good to know that makes me feel better thank you","nod"),
        ("Checkup is done and they say see you in six months. What do you say?",["thank you","see you","bye","appreciate","goodbye","will see","look forward","take care"],"Say goodbye","Thank you so much see you in six months goodbye and take care","wave"),
       ]),
     ]),
    # 30 at_library
    ("at_library","Asking the Librarian for Help","Practice asking for help finding a book, checking it out, and being polite.","📖","#EDE7F6","lb",
     "Wonderful! You found a book, got help from the librarian, and checked it out politely. A great skill! You earned a star!",
     [
      ("Let us practice visiting the library.",
       [("What can you do at a library?",["borrow books","read","study","research","computer","quiet","find","learn","check out"],"Name two things","I can borrow books and use it as a quiet place to study or research","think"),
        ("What should you keep in mind about library behavior?",["quiet","respectful","whisper","calm","no running","inside voice","phones off","noise"],"Say be quiet","I should keep my voice low and be respectful of others studying","nod"),
        ("What is a library card for?",["borrow","check out","take home","use system","ID","access","return","loan"],"Say: to borrow books","A library card lets me borrow books and other items and take them home","think"),
        ("Where would you go to find help in a library?",["desk","librarian","information desk","reference","ask","staff","help desk","counter"],"Say the help desk or librarian","I would go to the librarian at the help desk to ask for assistance","wave"),
        ("Ready to practice talking to a librarian?",["yes","ready","okay","sure","let us","go ahead","think so"],"Say yes","Yes I am ready to practice talking to a librarian","nod"),
       ]),
      ("Asking the librarian for help finding a book.",
       [("You approach the desk. What do you say?",["excuse me","hi","hello","could you help","looking for","need help","question"],"Start politely","Excuse me hi could you help me find a book please","wave"),
        ("They say sure. You want a fiction book. What do you say?",["looking for","fiction","novel","story","want","specific","genre","author","title","recommend"],"Describe what you want","I am looking for a fiction novel I enjoy mystery or adventure stories","think"),
        ("They ask if you have a specific author. What do you say?",["no","not really","open to","do not know","any","suggestions","you recommend","surprise me"],"Answer","I do not have a specific author in mind I am open to your suggestions","nod"),
        ("They recommend a book. What do you say?",["sounds great","like that","tell me more","what is it about","okay","interesting","might like"],"Show interest","That sounds really interesting what is it about","think"),
        ("They explain the plot. What do you say?",["love that","want to read","can I borrow","sounds perfect","great","take it","check out","yes"],"Say you want it","I love the sound of that I would love to check it out thank you","nod"),
       ]),
      ("Finding a book in the catalog.",
       [("The librarian shows you the computer catalog. What do they tell you to do?",["search","type","title","author","subject","system","find","enter","look up"],"Say you search for it","I would type in the title or author name to search for the book","think"),
        ("You type in a title and it shows the book is in. What does that mean?",["available","here","can borrow","on shelf","in library","not checked out","here now"],"Say it is available","It means the book is currently on the shelf and I can borrow it","nod"),
        ("The catalog shows it is in the 800s section. What do you do?",["find aisle","look for","go to","eight hundreds","shelf","section","ask","locate","search"],"Say you go to that section","I would go to the section labeled eight hundreds and look for it on the shelf","point"),
        ("You find the book. What do you do next?",["check out","desk","bring","counter","take to","borrow","scan","librarian"],"Take it to check out","I would bring it to the checkout desk to borrow it","point"),
        ("The librarian scans it. What do you say?",["thank you","thanks","appreciate","helpful","found it","great","all good"],"Thank them","Thank you so much for your help I found exactly what I wanted","nod"),
       ]),
      ("Checking out a book.",
       [("You bring the book to the desk. What do you say?",["hi","hello","check out","borrow","take out","would like","can I","scan"],"Ask to check out","Hi I would like to check this book out please","wave"),
        ("They ask for your library card. What do you say?",["here","have it","card","brought it","yes here","give them","hand over"],"Hand it over","Here is my library card thank you","nod"),
        ("They say it is due back in three weeks. What do you ask?",["renew","extend","if not back","what if","return late","can I","extend time","keep longer"],"Ask about renewal","Can I renew it if I need more time or is there a late fee","think"),
        ("They explain the policy. How do you respond?",["okay","understood","will return","on time","got it","alright","sure","know that","noted"],"Confirm","Okay I will make sure to return it on time or renew it if needed","nod"),
        ("You are about to leave. What do you say?",["thank you","thanks","appreciate","have a good","goodbye","bye","will be back","helpful"],"Say thank you and goodbye","Thank you so much have a great day goodbye","wave"),
       ]),
      ("Returning a book late.",
       [("You realize the book is late. What should you do?",["return","go back","bring back","late fee","tell them","return now","as soon as","right away"],"Return it right away","I should return it as soon as possible and expect there might be a small fee","point"),
        ("You arrive and tell the librarian the book is late. What do you say?",["sorry","late","returning this","overdue","past due","kept it too long","apologize"],"Be honest","Hi I am returning this book and I know it is a bit late I am sorry","sad"),
        ("They check and say there is a small fine. What do you say?",["okay","how much","how do I pay","fine","yes","ready","pay now","understand"],"Accept and pay","Okay how much is it and how can I pay the fine please","think"),
        ("They tell you the amount. What do you do?",["pay","here","card cash","give","hand over","pay now","sure","here you go"],"Pay the fine","Here you go and I will make sure to return books on time in the future","nod"),
        ("They say it is taken care of. What do you say?",["thank you","appreciate","sorry again","will not","will be on time","bye","sorry","goodbye"],"Thank them","Thank you and I am sorry for the inconvenience I will be more careful next time","wave"),
       ]),
      ("Asking for a recommendation.",
       [("You want something to read but do not know what. What do you say?",["excuse me","help","recommend","suggest","not sure what","something to read","any good","pick for me"],"Ask for help","Excuse me could you recommend a good book for a teenager who likes adventure","wave"),
        ("They ask what you have read recently. What do you say?",["read","last book","enjoyed","liked","recently","this series","that author","one I liked"],"Name something","I recently read a mystery novel and really enjoyed it","think"),
        ("They suggest a series. How do you ask about it?",["what is it","about","tell me","how many","similar","like","sound like","okay"],"Ask about it","What is the series about and is it similar to what I read","think"),
        ("They describe it and it sounds great. What do you say?",["sounds amazing","want to read","take the first","give me","can I borrow","interested","let us do it"],"Say you want it","That sounds amazing I would love to start with the first one","nod"),
        ("They hand you the book. What do you say?",["thank you","thanks","appreciate","helpful","great","excited","grateful","really helpful"],"Thank them","Thank you so much I am really excited to read this I appreciate your help","nod"),
       ]),
      ("Using the library for research.",
       [("You need to do a report. How can the library help?",["books","resources","reference","computer","database","find information","research","encyclopedia"],"Name a way","I can find reference books and use the library computers for research","think"),
        ("You ask for help finding non-fiction books on a topic. What do you say?",["excuse me","looking for","non fiction","research","topic","find books","on the subject","information on"],"Ask for help","Excuse me I am looking for non-fiction books on space exploration for a report","wave"),
        ("They guide you to the section. What do you say?",["thank you","appreciate","lead the way","show me","grateful","thanks for showing","follow"],"Thank them","Thank you I appreciate you showing me exactly where to look","nod"),
        ("You find two books. You want to check if there are more. What do you ask?",["more books","any other","online","database","search","catalog","more resources","anything else"],"Ask for more","Are there any other books or online resources I could use for this topic","think"),
        ("They point you to a database. How do you respond?",["thank you","great","will try","okay","sounds helpful","appreciate","use that","access it"],"Thank them and try it","Thank you I will try the database that is really helpful","nod"),
       ]),
      ("Full final library visit.",
       [("You enter and walk to the librarian desk. What do you say?",["hi","excuse me","hello","help","looking for","question","need","assist"],"Start politely","Hi excuse me I was hoping you could help me find something to read","wave"),
        ("They ask your interest. What do you say?",["like","enjoy","mystery","fantasy","adventure","real life","fiction","non fiction","anything good"],"Share your interest","I like mystery novels or anything with adventure I am pretty flexible","think"),
        ("They suggest something. What do you ask?",["what is it about","tell me","sounds","similar to","author","series","more info"],"Ask about it","Could you tell me a bit about it and who the author is","think"),
        ("You decide to borrow it. What do you say?",["great","sounds good","check out","borrow","yes","I will take","this one","perfect"],"Say you want it","I think I will borrow this one it sounds really good thank you","nod"),
        ("They scan it and hand it back. How do you close the visit?",["thank you","see you","bye","when to return","appreciate","due back","goodbye","helpful"],"Say goodbye politely","Thank you so much for your help I will have it back by the due date goodbye","wave"),
       ]),
     ]),
]

scenarios_list = []
all_nodes = {}

for row in SCENARIOS_DATA:
    sid, title, desc, emoji, color, prefix, win_say, acts_raw = row
    # build acts list from raw tuples
    acts = [(a[0], list(a[1])) for a in acts_raw]
    meta = {
        "id": sid, "title": title, "description": desc,
        "emoji": emoji, "color": color,
        "startNode": f"{prefix}_a1_bridge", "totalSteps": 8
    }
    scenarios_list.append(meta)
    all_nodes.update(make_nodes(sid, prefix, acts, win_say))

result = {"scenarios": scenarios_list, "nodes": all_nodes}
with open(OUT, "w", encoding="utf-8") as f:
    json.dump(result, f, ensure_ascii=False)

print(f"Written {len(scenarios_list)} scenarios, {len(all_nodes)} nodes to {OUT}")
